name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "clone-to-solid-pod"
      - uses: ./clone-to-solid-pod 
        with:
          input_path: /home/evemat/Dokumente/development/solid/dev/lib/
          target_container: https://solidweb.me/testpro/public/cloned/
          client_id: ${{ secrets.SOLID_CLIENT_ID }}
          client_secret: ${{ secrets.SOLID_CLIENT_SECRET }}
          oidc_issuer: https://solidweb.me/
